version: "3.3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123


  pgadmin:
      image: dpage/pgadmin4
      ports:
        - "8181:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: root@techmaster.vn
        PGADMIN_DEFAULT_PASSWORD: 123
        